### ISSUE TITLE
code

### ISSUE THREAD

**Issue by chl916185** [oliver-zrz-cyber/Co-LOD#1]
I'm very interested in your work(Architectural Co-LOD Generation), and do you have any plans to open source your code?
@oliver-zrz-cyber

**Comment by oliver-zrz-cyber** [comment]
@chl916185  Thank you for your interest in our project. Currently, the source code for this project is not open source due to some restrictive policies. We have made the API available at [https://oliver-zrz-cyber.github.io/Co-LOD/], and we plan further version updates to enhance usability and flexibility. We hope this meets your needs.
